version: '3.8'

services:
    app:
        build: .
        container_name: cfe_api
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_KEY=base64:gq0oGC6pFGRvEkTygtATcA1uWJXH8Dz7rAHq1N7TDUQ=
            - APP_DEBUG=true
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: cfe_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cfe
            MYSQL_USER: cfe
            MYSQL_PASSWORD: cfe
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    db_data: {}
